# Generated by Django 3.2 on 2024-10-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='appointment',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
