# Generated by Django 3.2 on 2024-10-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(default='0000', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.CharField(default='benie@gmail.com', max_length=100, unique=True),
        ),
    ]
